[project]
name = "rust-cargo"
description = "Rust with cargo reward"
tags = ["code", "rust", "single-turn"]
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "verifiers>=0.1.2.post0",
    "oxen",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["rust_cargo.py"]